name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Image
        run: docker build -t catapp:v1 .

      - name: Install Kind
        uses: helm/kind-action@v1.3.0
        with:
          version: v0.26.0

      - name: Create cluster with kind
        run: |
          kind create cluster --name local

      - name: Load Docker Image into Kind
        run: kind load docker-image catapp:v1 --name local

      - name: Install kubectl
        uses: Azure/setup-kubectl@v4
        with:
          version: 'v1.29.3'

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.14.0'

      - name: Deploy
        run: |
          helm upgrade --install catapp ./catapp \
            --namespace default \
            --kube-context kind-local | tee helm-deployment-output.log
        id: helm_deploy

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/catapp \
            --namespace default \
            --context kind-local

      - name: Port Forward svc
        run: |
          kubectl port-forward service/catapp 5001:5000 \
            --namespace default \
            --context kind-local &
        shell: bash

      - name: Wait
        run: sleep 10

      - name: Check health Endpoint
        run: |
          response=$(curl -f http://localhost:5001/health)
          echo "$response"

      - name: Test CatFact Endpoint
        run: |
          response=$(curl -f http://localhost:5001/joke/any)
          echo "$response"

      # Save Helm outputs as an artifact
      - name: Upload Helm Deployment Output Artifact
        uses: actions/upload-artifact@v3
        with:
          name: helm-deployment-output
          path: helm-deployment-output.log

      # Validate Ingress Resource
      - name: Validate Ingress
        run: |
          kubectl describe ingress catapp --namespace default --context kind-local | tee ingress-description.log
          kubectl get ingress catapp --namespace default --context kind-local -o yaml | tee ingress-yaml-output.log

      # Upload Ingress Description Artifact
      - name: Upload Ingress Description Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ingress-description
          path: ingress-description.log

      - name: Upload Ingress YAML Output Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ingress-yaml-output
          path: ingress-yaml-output.log
